# Product data for the JC Smart Picks page.
# (section_id, heading, [(ASIN, emoji, name, one-line description), ...], optional note)
SECTIONS = [
 ("featured", "🔥 Featured in our latest videos", [
  ("B0GPN9R146","✨","Happi Planet Magic Eraser (Pack of 4)","Diwali deep-cleaning for walls, switchboards & tiles"),
  ("B0BBFCG66M","🪔","DesiDiya LED Pixel String Lights (Warm White, ~10 m)","Budget balcony, mirror & pooja-corner glow"),
 ]),
 ("sale", "🎉 Great Indian Festival Picks", [
  ("B0DYDPBM8K","📱","Samsung Galaxy A56 5G (8 GB / 128 GB)","50MP triple camera with AI photo-editing features"),
  ("B0FMDL81GS","🎧","OnePlus Nord Buds 3r TWS Earbuds","2-mic clear calls & 3D spatial audio"),
  ("B0BJ72WZQ7","⌚","Noise Twist Round-Dial Smartwatch","Bluetooth calling with 100+ watch faces"),
  ("B09B8XJDW5","🔊","Amazon Echo Dot (5th Gen) Smart Speaker","Alexa for music, reminders & smart-home control"),
  ("B0FH569G3V","🍟","Lifelong Smartchoice 4.2 L Digital Air Fryer","7 preset menus, touch panel, non-stick basket"),
  ("B0CHJNJJDP","🌀","atomberg Renesa Enzel 1200 mm BLDC Ceiling Fan","BLDC motor fan with remote & LED speed indicator"),
  ("B0DCZ3WDTB","🔋","Xiaomi Power Bank 4i 20000 mAh","33 W fast charging, Type-C in & out"),
  ("B0F84FBWQM","📺","Samsung 32-inch HD Smart LED TV","Compact smart TV for bedroom or hall"),
  ("B0F3JH6RTG","📿","PALMONAS 18k Gold Plated Beaded Bliss Necklace","Listed as waterproof & anti-tarnish, an easy gift"),
  ("B0DHSBBV6R","🏎️","LEGO Speed Champions Ferrari SF-24 F1 Car (77242)","Building set for ages 10+"),
 ], "Sale deals change fast — check today's price on Amazon.in."),
 ("diwali-decor", "🪔 Diwali Décor & Lights", [
  ("B0DFZ579HK","💧","PulGos Water Sensor LED Diyas (36 pcs)","Reusable diyas that glow when placed in water, no smoke"),
  ("B0CVGY985K","🍃","One94Store Leaf Curtain Lights (200 LED, 3×1 m)","Warm-white curtain with remote for windows & walls"),
  ("B0BD43W4YP","✨","Crompton Galaxy USB Copper Fairy Lights (10 m)","100 warm-white LEDs to wrap shelves, jars & mirrors"),
  ("B0FDBFF8JM","🕯️","VERVENIX LED Tea Light Candles (Pack of 24)","Battery-operated flameless glow, no wax or smoke"),
  ("B0B63HWLGL","🪷","Divyakosh Lotus Wall Hangings (Set of 6)","Handmade jhumki-style décor for mandir & entrance"),
  ("B0CM2485RJ","🚪","Divyakosh Shubh Labh Door Hangings (1 Pair)","Golden side hangings for the main door"),
 ]),
 ("pooja", "🙏 Pooja & Rangoli", [
  ("B0DSZH4Y1H","🔥","ServDharm Brass Akhand Diya","Adjustable wick knob with a borosilicate glass cover"),
  ("B0BFC91NG5","🎨","Ascension Rangoli Making Kit (12 Designs)","Om, Swastik & flower stamps for quick rangoli"),
  ("B0BYQ8T4YD","💎","CentraLit Crystal Tealight Candle Holder","Sparkly holder for diyas & tealights"),
 ]),
 ("gifts", "🎁 Diwali Gifts", [
  ("B0H71SYY4J","🎁","AuraDecor Divine Pooja Gift Hamper","Lotus urli candle, dhoop cones, havan cups & diyas"),
  ("B09F8G2BDX","🥜","PrettyNutty Diwali Dry Fruits Gift (400 g)","Almonds, cashews, pistachios & raisins, 100 g each"),
  ("B099WR4WHC","⌚","Fastrack Tees Analog Unisex Watch","Diwali / Bhai Dooj gift idea"),
  ("B0H155N39C","💎","Shining Diva 12-Pair Earrings Set with Box","Ready-to-gift for sister or friend"),
 ]),
 ("home-kitchen", "🏠 Home & Kitchen", [
  ("B0F8HJJVW1","☕","Nova Rechargeable Electric Milk Frother","Café-style coffee for Diwali guests"),
  ("B0C897PVVM","🧄","AGARO Elite Rechargeable Mini Chopper 250 ml","Quick festive cooking prep"),
  ("B0DN1RWNSQ","🌌","One94Store Nebula Star Projector Night Light","Galaxy room makeover, great kids' gift"),
  ("B008XT42JU","🔌","GM 3060 Extension Board (4 Sockets, 2 m)","Master switch & safety shutters, handy for Diwali lights"),
  ("B078S7CDLT","🥡","Borosil Klip N Store Square Glass Containers (Set of 2)","Air-tight glass boxes for sweets & leftovers"),
  ("B0F54GKQ38","♨️","Milton Rapid Electric Kettle 1.8 L","1500 W stainless-steel kettle for tea & noodles"),
  ("B0B257ZYVB","🥚","AGARO Grand Egg Boiler & Poacher","Boils 8 eggs or poaches 4, also steams veggies"),
  ("B09J2T124D","🥤","NutriPro Juicer Mixer Grinder 500 W","2 jars for smoothies, juices & chutneys"),
 ]),
 ("gadgets", "🎧 Gadgets & Tech", [
  ("B0FBRGKXHG","🎵","OnePlus Bullets Wireless Z3 Neckband","12.4 mm drivers, quick 10-minute charge"),
  ("B0FLF44GTQ","⌚","boAt Wave Call 3 Smartwatch","1.83-inch display with Bluetooth calling"),
  ("B0DNFSSF3F","💾","SanDisk Ultra Dual Drive Go Type-C 128 GB","Pendrive to free up phone storage"),
  ("B0D9S87H53","🧲","Ambrane MagSafe Wireless Power Bank 10000 mAh","Magnetic snap-on charging, 22.5 W output"),
  ("B0FDQ9M1SD","🖱️","Portronics Toad 8 Transparent Wireless Mouse","See-through desk-setup look, BT + 2.4 GHz"),
  ("B08TV2P1N8","🎶","boAt Rockerz 255 Pro+ Neckband","Sale-season gift pick"),
  ("B0F63BY6LT","🤳","Kratos K9 Selfie Stick Tripod with Light","Family photos & rangoli time-lapses"),
  ("B0H5VWCNWN","📍","JioTag (2nd Gen) Item Finder","Track keys, wallets & bags, works with Android or iOS"),
  ("B0BBRJVLWD","⚡","Portronics Adapto 45 GaN Dual-Port Charger","22.5 W USB + Type-C wall adapter"),
  ("B082LSVT4B","🔋","Ambrane 60W Braided Type-C to Type-C Cable (1.5 m)","Fast charging for phones, tablets & laptops"),
  ("B08MCD9JFY","💡","Tygot 10-inch LED Ring Light","For Reels, video calls & makeup"),
 ]),
 ("beauty", "💄 Beauty", [
  ("B0CND1VF2W","💋","WishCare Tinted Lip Balm SPF 50 PA++++","Tint + SPF for festive outdoor days"),
  ("B08FW1GJ4F","💇","L'Oréal Paris Extraordinary Oil Hair Serum 100 ml","Festive hair styling, hamper add-on"),
  ("B09FPS9D5T","🧴","Minimalist Sunscreen SPF 50 PA++++","Niacinamide sunscreen for everyday use"),
  ("B00YJJWBUA","💄","Maybelline Color Sensational Creamy Matte Lipstick","Festive-look lipstick in many shades"),
  ("B01CCGW4OE","🫧","Cetaphil Gentle Skin Hydrating Face Wash 118 ml","Paraben- & sulphate-free gentle cleanser"),
  ("B08M4T5FJG","🧴","Vaseline Deep Moisture Body Lotion","Ceramide lotion for dry winter skin"),
 ]),
 ("toys", "🧸 Toys & Kids", [
  ("B09VC3KD86","✏️","Portronics Ruffpad 12M LCD Writing Pad","Re-writable 12-inch pad with one-tap erase"),
  ("B00004TZY8","🃏","Mattel UNO Card Game","Classic family game for Diwali get-togethers"),
  ("B0GQ89XY15","🧩","Storio 3D Magnetic Tiles (28 pcs)","STEM building toy for ages 3–8"),
 ]),
]
